[project]
name = "demo-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.123.4",
    "pydantic>=2.12.5",
    "uvicorn>=0.38.0",
]
